spring.datasource.url: jdbc:postgresql://192.168.5.89:5432/todolist
spring.datasource.username: postgres
spring.datasource.password: Ac12345678

# Hibernate ddl auto (create, create-drop, validate, update)
spring.jpa.hibernate.ddl-auto: create
